server:
  port: 8081

spring:
  application:
    name: storage
  data:
    mongodb:
      uri: ${mongo-connection}
      database: ${mongo-database}

thor:
  azure:
    connection-string: ${azure-connection}
    container: ${azure-container}

springdoc:
  swagger-ui:
    path: /
