server:
  port: 8081

spring:
  application:
    name: storage
  data:
    mongodb:
      uri: ${mongo-connection}
      database: ${mongo-database}

thor:
  azure:
    connection-string: ${azure-connection}
    container: ${azure-container}

springdoc:
  swagger-ui:
    path: /

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-url}